services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

